# web-calculator-golang\config\config.yaml
server:
  ORC_HOST: localhost
  ORC_PORT: 8080
  AG_HOST: localhost
  AG_PORT: 8000

duration:
  TIME_ADDITION_MS: 100
  TIME_SUBTRACTION_MS: 100
  TIME_MULTIPLICATIONS_MS: 100
  TIME_DIVISIONS_MS: 100

worker:
  COMPUTING_POWER: 5

database:
  DATABASE_PATH: ./db/calc.db